import { GhosttyConfig, ConfigKey } from '../types/config';
import { defaultConfig } from '../data/configSchema';

// Map from our camelCase keys to Ghostty's kebab-case config keys
const keyMapping: Record<ConfigKey, string> = {
  fontFamily: 'font-family',
  fontSize: 'font-size',
  fontStyleBold: 'font-style-bold',
  fontStyleItalic: 'font-style-italic',
  fontStyleBoldItalic: 'font-style-bold-italic',
  fontThicken: 'font-thicken',
  fontSyntheticStyle: 'font-synthetic-style',
  adjustCellWidth: 'adjust-cell-width',
  adjustCellHeight: 'adjust-cell-height',
  theme: 'theme',
  background: 'background',
  foreground: 'foreground',
  cursorColor: 'cursor-color',
  cursorText: 'cursor-text',
  selectionBackground: 'selection-background',
  selectionForeground: 'selection-foreground',
  backgroundOpacity: 'background-opacity',
  minimumContrast: 'minimum-contrast',
  palette: 'palette',
  cursorStyle: 'cursor-style',
  cursorStyleBlink: 'cursor-style-blink',
  cursorOpacity: 'cursor-opacity',
  cursorClickToMove: 'cursor-click-to-move',
  windowWidth: 'window-width',
  windowHeight: 'window-height',
  windowPaddingX: 'window-padding-x',
  windowPaddingY: 'window-padding-y',
  windowPaddingBalance: 'window-padding-balance',
  windowPaddingColor: 'window-padding-color',
  windowDecoration: 'window-decoration',
  windowTheme: 'window-theme',
  windowVsync: 'window-vsync',
  fullscreen: 'fullscreen',
  maximize: 'maximize',
  backgroundBlurRadius: 'background-blur-radius',
  title: 'title',
  className: 'class',
  initialWindow: 'initial-window',
  resizeOverlay: 'resize-overlay',
  focusFollowsMouse: 'focus-follows-mouse',
  mouseHideWhileTyping: 'mouse-hide-while-typing',
  mouseScrollMultiplier: 'mouse-scroll-multiplier',
  scrollbackLimit: 'scrollback-limit',
  copyOnSelect: 'copy-on-select',
  clipboardRead: 'clipboard-read',
  clipboardWrite: 'clipboard-write',
  clipboardPasteProtection: 'clipboard-paste-protection',
  clipboardTrimTrailingSpaces: 'clipboard-trim-trailing-spaces',
  shellIntegration: 'shell-integration',
  shellIntegrationFeatures: 'shell-integration-features',
  command: 'command',
  workingDirectory: 'working-directory',
  keybindings: 'keybind',
  imageStorageLimit: 'image-storage-limit',
  confirmCloseSurface: 'confirm-close-surface',
  titleReport: 'title-report',
  enquiryResponse: 'enquiry-response',
  boldIsBright: 'bold-is-bright',
  termEnv: 'term',
  autoUpdate: 'auto-update',
  customShaderAnimation: 'custom-shader-animation',
};

function formatValue(value: unknown): string {
  if (typeof value === 'boolean') {
    return value ? 'true' : 'false';
  }
  if (typeof value === 'number') {
    return value.toString();
  }
  return String(value);
}

function isDefaultValue(key: ConfigKey, value: unknown): boolean {
  const defaultValue = defaultConfig[key];

  if (Array.isArray(value) && Array.isArray(defaultValue)) {
    if (value.length !== defaultValue.length) return false;
    return value.every((v, i) => v === defaultValue[i]);
  }

  return value === defaultValue;
}

function shouldIncludeOption(key: ConfigKey, value: unknown): boolean {
  // Skip default values
  if (isDefaultValue(key, value)) {
    return false;
  }

  // Skip empty strings
  if (value === '') {
    return false;
  }

  // Skip empty arrays
  if (Array.isArray(value) && value.length === 0) {
    return false;
  }

  // Skip zero values for certain window dimensions
  if ((key === 'windowWidth' || key === 'windowHeight') && value === 0) {
    return false;
  }

  return true;
}

export function generateConfig(config: GhosttyConfig): string {
  const lines: string[] = [];
  lines.push('# Ghostty Configuration');
  lines.push('# Generated by Ghostty Config Generator');
  lines.push('');

  const categories: Record<string, ConfigKey[]> = {
    '# Font Settings': ['fontFamily', 'fontSize', 'fontStyleBold', 'fontStyleItalic', 'fontStyleBoldItalic', 'fontThicken', 'fontSyntheticStyle', 'adjustCellWidth', 'adjustCellHeight'],
    '# Colors & Theme': ['theme', 'background', 'foreground', 'cursorColor', 'cursorText', 'selectionBackground', 'selectionForeground', 'backgroundOpacity', 'minimumContrast'],
    '# Cursor': ['cursorStyle', 'cursorStyleBlink', 'cursorOpacity', 'cursorClickToMove'],
    '# Window': ['windowWidth', 'windowHeight', 'windowPaddingX', 'windowPaddingY', 'windowPaddingBalance', 'windowPaddingColor', 'windowDecoration', 'windowTheme', 'windowVsync', 'fullscreen', 'maximize', 'backgroundBlurRadius', 'title', 'focusFollowsMouse'],
    '# Mouse & Scrolling': ['mouseHideWhileTyping', 'mouseScrollMultiplier', 'scrollbackLimit'],
    '# Clipboard': ['copyOnSelect', 'clipboardRead', 'clipboardWrite', 'clipboardPasteProtection', 'clipboardTrimTrailingSpaces'],
    '# Shell Integration': ['shellIntegration', 'shellIntegrationFeatures', 'command', 'workingDirectory'],
    '# Keybindings': ['keybindings'],
    '# Advanced': ['imageStorageLimit', 'confirmCloseSurface', 'titleReport', 'enquiryResponse', 'boldIsBright', 'termEnv', 'autoUpdate', 'customShaderAnimation'],
  };

  for (const [sectionComment, keys] of Object.entries(categories)) {
    const sectionLines: string[] = [];

    for (const key of keys) {
      const value = config[key];
      const ghosttyKey = keyMapping[key];

      if (!shouldIncludeOption(key, value)) {
        continue;
      }

      // Handle keybindings specially
      if (key === 'keybindings' && Array.isArray(value)) {
        for (const binding of value as { key: string; action: string }[]) {
          if (binding.key && binding.action) {
            sectionLines.push(`keybind = ${binding.key}=${binding.action}`);
          }
        }
        continue;
      }

      // Handle shell integration features
      if (key === 'shellIntegrationFeatures' && Array.isArray(value)) {
        for (const feature of value) {
          sectionLines.push(`${ghosttyKey} = ${feature}`);
        }
        continue;
      }

      // Handle palette
      if (key === 'palette' && Array.isArray(value)) {
        value.forEach((color, index) => {
          if (color) {
            sectionLines.push(`palette = ${index}=${color}`);
          }
        });
        continue;
      }

      sectionLines.push(`${ghosttyKey} = ${formatValue(value)}`);
    }

    if (sectionLines.length > 0) {
      lines.push(sectionComment);
      lines.push(...sectionLines);
      lines.push('');
    }
  }

  // Remove trailing empty lines
  while (lines.length > 0 && lines[lines.length - 1] === '') {
    lines.pop();
  }

  return lines.join('\n');
}
